### ISSUE TITLE
recaptcha break token..

### ISSUE THREAD

**Issue by gembes** [backdrop-contrib/recaptcha#1]
when activate recaptcha, backdrop token failed to load token.
![selection_002](https://cloud.githubusercontent.com/assets/20469101/22182902/64275c98-e0e3-11e6-9cdc-77f31cf8fa2a.png)

![selection_003](https://cloud.githubusercontent.com/assets/20469101/22182911/9d625c2e-e0e3-11e6-886d-4e48764811c6.png)

**Comment by herbdool** [comment]
Do you have the same problem if you're just using Captcha?

I'm going to try to narrow the possible errors.

Can you also try get the error again and paste here any error messages you see in under Report > Recent Log Messages that you see for the same time. Thank you

**Comment by herbdool** [comment]
@gembes If you are up for testing before I make an official update, I've applied a patch to this branch: https://github.com/backdrop-contrib/recaptcha/tree/ajaxfix

I'm also testing to ensure that it fixes this issue and that it doesn't make anything else worse.

**Comment by herbdool** [comment]
I've tested on a couple other sites and this patch isn't working. And I retested on my original test site by uninstalling and reinstalling. Now it doesn't work. Curious. So there's more work required here.

**Comment by gembes** [comment]
> Do you have the same problem if you're just using Captcha?

when only captcha, token running w/o problem

**Comment by herbdool** [comment]
I'm going to get back to this soon. In the meanwhile I recommend disabling recaptcha while you're developing the site. I suspect that it's not so much tokens as the popup modal that is affected by recaptcha, so it might be okay to have recaptcha enabled after development.

**Comment by herbdool** [comment]
I've made a new release which in my own testing allows token browsing to work properly. Please test and reopen if you still have issues @gembes
